version: '3.8'

services:
  kafka:
    networks: [monitoring-net]
    image: confluentinc/cp-kafka:8.1.0-1-ubi9
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_COMPRESSION_TYPE: 'snappy'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    # volumes:
    #   - kafka-data:/var/lib/kafka/data

  mysql:
    networks: [monitoring-net]
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --plugin-load-add=mysql_native_password.so
      --performance-schema=ON
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/mysql-slow.log
      --long-query-time=0.01
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-init/init_exporter_user.sql:/docker-entrypoint-initdb.d/init_exporter_user.sql
    #   - mysql-data:/var/lib/mysql

  redis:
    networks: [monitoring-net]
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    # volumes:
    #   - redis-data:/data

# volumes:
#   kafka-data:
#   mysql-data:
#   redis-data:

networks:
  monitoring-net:
    driver: bridge